# Generated by Django 4.1.7 on 2023-03-27 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_customuser_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
    ]
