# Generated by Django 4.1.7 on 2023-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0002_goal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="priority",
            field=models.IntegerField(
                choices=[
                    (1, "Низкий"),
                    (2, "Средний"),
                    (3, "Высокий"),
                    (4, "Критический"),
                ],
                verbose_name="Приоритет",
            ),
        ),
        migrations.AlterField(
            model_name="goal",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "К выполнению"),
                    (2, "В процессе"),
                    (3, "Выполнено"),
                    (4, "Архив"),
                ],
                verbose_name="Статус",
            ),
        ),
    ]
