# Generated by Django 4.1.7 on 2023-05-18 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goals", "0003_alter_goal_priority_alter_goal_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goal",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="goals.goalcategory",
                verbose_name="Категория",
            ),
        ),
    ]
